import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

const inter = Inter(
  { subsets: ["cyrillic"] }
);

export const metadata: Metadata = {
  title: "VSHOT - Продажа дроби и картечи",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>)   {
  return (
    <html lang="ru">
      <body className={inter.className + ' bg-background text-gray-400 text-base overflow-x-hidden'}>
        <div className="__next">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
